/** Firestore collection names — aligned with Android Party Connect app */
export const COLLECTIONS = {
  USERS: 'users',
  ADMINS: 'admins',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  LEADERS: 'leaders',
  POSTS: 'posts',
  COMMENTS: 'comments',
  LIKES: 'likes',
  SHARES: 'shares',
  NEWS: 'news',
  CATEGORIES: 'categories',
  EVENTS: 'events',
  GALLERY: 'gallery',
  VIDEOS: 'videos',
  MEDIA: 'media',
  DOWNLOADS: 'downloads',
  NOTIFICATIONS: 'notifications',
  POLLS: 'polls',
  VOTES: 'votes',
  FEEDBACK: 'feedback',
  REPORTS: 'reports',
  ANALYTICS: 'analytics',
  BANNERS: 'banners',
  ADVERTISEMENTS: 'advertisements',
  DISTRICTS: 'districts',
  MANDALS: 'mandals',
  VILLAGES: 'villages',
  DEPARTMENTS: 'departments',
  MEMBERSHIP: 'membership',
  VOLUNTEERS: 'volunteers',
  SETTINGS: 'settings',
  LOGS: 'logs',
  LIVE: 'live',
  PLANS: 'plans',
  SUBSCRIPTIONS: 'subscriptions',
  TRIAL_SETTINGS: 'trial_settings',
  PAYMENT_SETTINGS: 'payment_settings',
  PAYMENT_TRANSACTIONS: 'payment_transactions',
  SUBSCRIPTION_HISTORY: 'subscription_history',
  FEATURE_PERMISSIONS: 'feature_permissions',
  INVOICES: 'invoices',
  // Public website
  WEBSITE_SETTINGS: 'website_settings',
  WEBSITE_STATISTICS: 'website_statistics',
  WEBSITE_QUICK_ACTIONS: 'website_quick_actions',
  DISTRICT_COMMITTEES: 'district_committees',
  EMPLOYEE_ISSUES: 'employee_issues',
  WELFARE_SCHEMES: 'welfare_schemes',
  GOVERNMENT_ORDERS: 'government_orders',
  GRIEVANCES: 'grievances',
  CONTACT_MESSAGES: 'contact_messages',
  SPONSORS: 'sponsors',
  PRESS_NOTES: 'press_notes',
  CIRCULARS: 'circulars',
  COURT_ORDERS: 'court_orders',
};

export const STORAGE_PATHS = {
  LEADERS: 'leaders/',
  NEWS: 'news/',
  POSTS: 'posts/',
  GALLERY: 'gallery/',
  VIDEOS: 'videos/',
  DOCUMENTS: 'documents/',
  DOWNLOADS: 'downloads/',
  PROFILE: 'profile/',
  BANNERS: 'banners/',
  ADS: 'ads/',
  CERTIFICATES: 'certificates/',
  PLANS: 'plans/',
  WEBSITE: 'website/',
};

export const FIELDS = {
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
  TITLE: 'title',
  NAME: 'name',
  EMAIL: 'email',
  STATUS: 'status',
  ROLE: 'role',
  IS_ACTIVE: 'is_active',
};
