import { COLLECTIONS, STORAGE_PATHS } from '@/firebase/collections';

const baseFields = {
  title: { name: 'title', label: 'Title', type: 'text', required: true },
  name: { name: 'name', label: 'Name', type: 'text', required: true },
  description: { name: 'description', label: 'Description', type: 'textarea' },
  status: { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'pending', 'draft', 'published', 'archived', 'blocked', 'suspended'] },
  category: { name: 'category', label: 'Category', type: 'text' },
  image: { name: 'image_url', label: 'Image', type: 'image', storage: STORAGE_PATHS.GALLERY },
  sponsor_logo: { name: 'logo_url', label: 'Sponsor Logo', type: 'image', storage: STORAGE_PATHS.WEBSITE },
  priority: { name: 'priority', label: 'Priority', type: 'number' },
  is_active: { name: 'is_active', label: 'Active', type: 'switch' },
  email: { name: 'email', label: 'Email', type: 'email' },
  mobile: { name: 'mobile', label: 'Mobile', type: 'text' },
  role: { name: 'role', label: 'Role', type: 'select', options: ['admin', 'moderator', 'editor', 'viewer', 'district_admin', 'state_admin'] },
  district: { name: 'district', label: 'District', type: 'text' },
  mandal: { name: 'mandal', label: 'Mandal', type: 'text' },
  village: { name: 'village', label: 'Village', type: 'text' },
  designation: { name: 'designation', label: 'Designation', type: 'text' },
  biography: { name: 'biography', label: 'Biography', type: 'richtext' },
  video_url: { name: 'video_url', label: 'Video URL', type: 'text' },
  stream_url: { name: 'stream_url', label: 'Stream URL', type: 'text' },
  is_live: { name: 'is_live', label: 'Live Now', type: 'switch' },
  location: { name: 'location', label: 'Venue', type: 'text' },
  scheduled_at: { name: 'scheduled_at', label: 'Scheduled At', type: 'datetime' },
  end_date: { name: 'end_date', label: 'End Date', type: 'datetime' },
  file_url: {
    name: 'file_url',
    label: 'PDF Document',
    type: 'file',
    storage: STORAGE_PATHS.DOCUMENTS,
    accept: { 'application/pdf': ['.pdf'] },
  },
  go_category: {
    name: 'category',
    label: 'Category',
    type: 'select',
    required: true,
    options: ["GO's", 'Proceedings', 'Circulars', 'Notifications', 'Court Orders'],
  },
  go_pdf: {
    name: 'file_url',
    label: 'PDF Document',
    type: 'file',
    storage: STORAGE_PATHS.DOCUMENTS,
    accept: { 'application/pdf': ['.pdf'] },
    required: true,
  },
  link_url: { name: 'link_url', label: 'Link URL', type: 'text' },
  content: { name: 'content', label: 'Content', type: 'richtext' },
  membership_id: { name: 'membership_id', label: 'Membership #', type: 'text' },
  booth_number: { name: 'booth_number', label: 'Booth #', type: 'text' },
  fcm_token: { name: 'fcm_token', label: 'FCM Token', type: 'text' },
  message: { name: 'message', label: 'Message', type: 'textarea' },
  type: { name: 'type', label: 'Type', type: 'text' },
  target_screen: { name: 'target_screen', label: 'Target Screen', type: 'text' },
  target_id: { name: 'target_id', label: 'Target Item ID', type: 'text' },
  user_id: { name: 'user_id', label: 'User ID (use "all" for broadcast)', type: 'text' },
  ad_type: { name: 'ad_type', label: 'Ad Type', type: 'select', options: ['banner', 'popup', 'slider', 'interstitial', 'native'] },
  banner_type: { name: 'banner_type', label: 'Banner Type', type: 'select', options: ['home', 'news', 'event', 'offer'] },
  skills: { name: 'skills', label: 'Skills', type: 'text' },
  reply: { name: 'reply', label: 'Reply', type: 'textarea' },
  options: { name: 'options', label: 'Options (comma separated)', type: 'text' },
  vote_count: { name: 'vote_count', label: 'Votes', type: 'number', readOnly: true },
  view_count: { name: 'view_count', label: 'Views', type: 'number', readOnly: true },
  like_count: { name: 'like_count', label: 'Likes', type: 'number', readOnly: true },
  comment_count: { name: 'comment_count', label: 'Comments', type: 'number', readOnly: true },
  plan_name: { name: 'plan_name', label: 'Plan', type: 'text' },
  plan_id: { name: 'plan_id', label: 'Plan ID', type: 'text' },
  price: { name: 'price', label: 'Price (₹)', type: 'number' },
  currency: { name: 'currency', label: 'Currency', type: 'text' },
  validity_days: { name: 'validity_days', label: 'Validity (Days)', type: 'number' },
  display_order: { name: 'display_order', label: 'Display Order', type: 'number' },
  is_recommended: { name: 'is_recommended', label: 'Recommended', type: 'switch' },
  trial_eligible: { name: 'trial_eligible', label: 'Trial Eligible', type: 'switch' },
  features: { name: 'features', label: 'Features (one per line)', type: 'textarea' },
  subscription_status: { name: 'subscription_status', label: 'Status', type: 'select', options: ['trial', 'active', 'expired', 'cancelled'] },
  payment_status: { name: 'payment_status', label: 'Payment Status', type: 'select', options: ['none', 'pending', 'paid', 'failed', 'refunded'] },
  amount: { name: 'amount', label: 'Amount', type: 'number' },
  razorpay_order_id: { name: 'razorpay_order_id', label: 'Razorpay Order ID', type: 'text', readOnly: true },
  transaction_id: { name: 'transaction_id', label: 'Transaction ID', type: 'text', readOnly: true },
  district_name: { name: 'district_name', label: 'District Name', type: 'text', required: true },
  president: { name: 'president', label: 'President', type: 'text' },
  secretary: { name: 'secretary', label: 'Secretary', type: 'text' },
  total_members: { name: 'total_members', label: 'Total Members', type: 'number' },
  eligibility: { name: 'eligibility', label: 'Eligibility', type: 'textarea' },
  value: { name: 'value', label: 'Value', type: 'text', required: true },
  suffix: { name: 'suffix', label: 'Suffix', type: 'text' },
  icon: { name: 'icon', label: 'Icon Key', type: 'text' },
  color: { name: 'color', label: 'Color (hex)', type: 'text' },
  link: { name: 'link', label: 'Link Path', type: 'text' },
  subject: { name: 'subject', label: 'Subject', type: 'text' },
  qr_image: { name: 'qr_code_url', label: 'QR Code Image', type: 'image', storage: STORAGE_PATHS.WEBSITE },
};

export const MODULES = {
  users: {
    collection: COLLECTIONS.USERS,
    module: 'users',
    title: 'Users',
    singular: 'User',
    columns: ['name', 'email', 'mobile', 'role', 'district', 'status', 'created_at'],
    formFields: ['name', 'email', 'mobile', 'role', 'district', 'mandal', 'village', 'membership_id', 'booth_number', 'status', 'image'],
    storagePath: STORAGE_PATHS.PROFILE,
  },
  leaders: {
    collection: COLLECTIONS.LEADERS,
    module: 'leaders',
    title: 'Leaders',
    singular: 'Leader',
    columns: ['name', 'designation', 'district', 'priority', 'is_active', 'created_at'],
    formFields: ['name', 'designation', 'biography', 'district', 'priority', 'is_active', 'image', 'video_url'],
    storagePath: STORAGE_PATHS.LEADERS,
  },
  news: {
    collection: COLLECTIONS.NEWS,
    module: 'news',
    title: 'News',
    singular: 'News',
    columns: ['title', 'category', 'status', 'view_count', 'created_at'],
    formFields: ['title', 'category', 'content', 'status', 'image', 'scheduled_at'],
    storagePath: STORAGE_PATHS.NEWS,
  },
  posts: {
    collection: COLLECTIONS.POSTS,
    module: 'posts',
    title: 'Posts',
    singular: 'Post',
    columns: ['content', 'author_name', 'like_count', 'comment_count', 'status', 'created_at'],
    formFields: ['content', 'status', 'image', 'video_url'],
    storagePath: STORAGE_PATHS.POSTS,
  },
  media: {
    collection: COLLECTIONS.MEDIA,
    module: 'media',
    title: 'Media',
    singular: 'Media',
    columns: ['title', 'category', 'type', 'created_at'],
    formFields: ['title', 'category', 'type', 'file_url', 'image'],
    storagePath: STORAGE_PATHS.DOCUMENTS,
  },
  gallery: {
    collection: COLLECTIONS.GALLERY,
    module: 'gallery',
    title: 'Gallery',
    singular: 'Album',
    columns: ['title', 'category', 'priority', 'created_at'],
    formFields: ['title', 'category', 'description', 'priority', 'image'],
    storagePath: STORAGE_PATHS.GALLERY,
  },
  videos: {
    collection: COLLECTIONS.VIDEOS,
    module: 'videos',
    title: 'Videos',
    singular: 'Video',
    columns: ['title', 'category', 'view_count', 'created_at'],
    formFields: ['title', 'category', 'video_url', 'description', 'image'],
    storagePath: STORAGE_PATHS.VIDEOS,
  },
  live: {
    collection: COLLECTIONS.LIVE,
    module: 'live',
    title: 'Live Streaming',
    singular: 'Live Event',
    columns: ['title', 'is_live', 'stream_url', 'scheduled_at', 'created_at'],
    formFields: ['title', 'description', 'stream_url', 'is_live', 'scheduled_at', 'image'],
    storagePath: STORAGE_PATHS.VIDEOS,
  },
  events: {
    collection: COLLECTIONS.EVENTS,
    module: 'events',
    title: 'Events',
    singular: 'Event',
    columns: ['title', 'location', 'district', 'scheduled_at', 'status'],
    formFields: ['title', 'description', 'location', 'district', 'scheduled_at', 'status', 'image'],
    storagePath: STORAGE_PATHS.DOCUMENTS,
  },
  polls: {
    collection: COLLECTIONS.POLLS,
    module: 'polls',
    title: 'Polls',
    singular: 'Poll',
    columns: ['title', 'vote_count', 'end_date', 'status', 'created_at'],
    formFields: ['title', 'options', 'end_date', 'status'],
    storagePath: STORAGE_PATHS.DOCUMENTS,
  },
  comments: {
    collection: COLLECTIONS.COMMENTS,
    module: 'comments',
    title: 'Comments',
    singular: 'Comment',
    columns: ['content', 'user_id', 'post_id', 'status', 'created_at'],
    formFields: ['content', 'status'],
    readOnlyForm: true,
  },
  notifications: {
    collection: COLLECTIONS.NOTIFICATIONS,
    module: 'notifications',
    title: 'Notifications',
    singular: 'Notification',
    columns: ['title', 'description', 'target_screen', 'user_id', 'created_at'],
    formFields: ['title', 'description', 'target_screen', 'target_id', 'user_id', 'status'],
  },
  advertisements: {
    collection: COLLECTIONS.ADVERTISEMENTS,
    module: 'advertisements',
    title: 'Advertisements',
    singular: 'Advertisement',
    columns: ['title', 'ad_type', 'priority', 'is_active', 'created_at'],
    formFields: ['title', 'ad_type', 'link_url', 'priority', 'is_active', 'image'],
    storagePath: STORAGE_PATHS.ADS,
  },
  banners: {
    collection: COLLECTIONS.BANNERS,
    module: 'banners',
    title: 'Banners',
    singular: 'Banner',
    columns: ['title', 'banner_type', 'priority', 'is_active'],
    formFields: ['title', 'banner_type', 'link_url', 'priority', 'is_active', 'image'],
    storagePath: STORAGE_PATHS.BANNERS,
  },
  downloads: {
    collection: COLLECTIONS.DOWNLOADS,
    module: 'downloads',
    title: 'Downloads',
    singular: 'Download',
    columns: ['title', 'category', 'file_type', 'created_at'],
    formFields: ['title', 'category', 'description', 'file_url'],
    storagePath: STORAGE_PATHS.DOWNLOADS,
  },
  districts: {
    collection: COLLECTIONS.DISTRICTS,
    module: 'districts',
    title: 'Districts',
    singular: 'District',
    columns: ['name', 'status', 'created_at'],
    formFields: ['name', 'description', 'status'],
  },
  mandals: {
    collection: COLLECTIONS.MANDALS,
    module: 'mandals',
    title: 'Mandals',
    singular: 'Mandal',
    columns: ['name', 'district', 'status'],
    formFields: ['name', 'district', 'status'],
  },
  villages: {
    collection: COLLECTIONS.VILLAGES,
    module: 'villages',
    title: 'Villages',
    singular: 'Village',
    columns: ['name', 'mandal', 'district', 'status'],
    formFields: ['name', 'mandal', 'district', 'status'],
  },
  departments: {
    collection: COLLECTIONS.DEPARTMENTS,
    module: 'departments',
    title: 'Departments',
    singular: 'Department',
    columns: ['name', 'status', 'created_at'],
    formFields: ['name', 'description', 'status'],
  },
  membership: {
    collection: COLLECTIONS.MEMBERSHIP,
    module: 'membership',
    title: 'Membership',
    singular: 'Membership',
    columns: ['name', 'membership_id', 'district', 'status'],
    formFields: ['name', 'membership_id', 'district', 'mandal', 'village', 'status'],
  },
  volunteers: {
    collection: COLLECTIONS.VOLUNTEERS,
    module: 'volunteers',
    title: 'Volunteers',
    singular: 'Volunteer',
    columns: ['name', 'district', 'booth_number', 'skills', 'status'],
    formFields: ['name', 'mobile', 'email', 'district', 'booth_number', 'skills', 'status'],
  },
  feedback: {
    collection: COLLECTIONS.FEEDBACK,
    module: 'feedback',
    title: 'Feedback',
    singular: 'Feedback',
    columns: ['type', 'message', 'status', 'created_at'],
    formFields: ['type', 'message', 'status', 'reply'],
  },
  reports: {
    collection: COLLECTIONS.REPORTS,
    module: 'reports',
    title: 'Reports',
    singular: 'Report',
    columns: ['title', 'type', 'status', 'created_at'],
    formFields: ['title', 'type', 'description', 'status'],
  },
  payment_transactions: {
    collection: COLLECTIONS.PAYMENT_TRANSACTIONS,
    module: 'payment_transactions',
    title: 'Payment Transactions',
    singular: 'Transaction',
    columns: ['user_id', 'plan_name', 'amount', 'payment_status', 'razorpay_order_id', 'created_at'],
    formFields: ['user_id', 'plan_name', 'amount', 'payment_status', 'razorpay_order_id', 'transaction_id'],
    readOnlyForm: true,
  },
  subscription_history: {
    collection: COLLECTIONS.SUBSCRIPTION_HISTORY,
    module: 'subscription_history',
    title: 'Subscription History',
    singular: 'History Entry',
    columns: ['user_id', 'action', 'plan_id', 'created_at'],
    formFields: ['user_id', 'action', 'plan_id'],
    readOnlyForm: true,
  },
  invoices: {
    collection: COLLECTIONS.INVOICES,
    module: 'invoices',
    title: 'Invoices',
    singular: 'Invoice',
    columns: ['user_id', 'plan_name', 'amount', 'currency', 'status', 'created_at'],
    formFields: ['user_id', 'plan_name', 'amount', 'currency', 'payment_id', 'transaction_id', 'status'],
    readOnlyForm: true,
  },
  roles: {
    collection: COLLECTIONS.ROLES,
    module: 'roles',
    title: 'Roles',
    singular: 'Role',
    columns: ['name', 'role', 'status', 'created_at'],
    formFields: ['name', 'role', 'description', 'status'],
  },
  district_committees: {
    collection: COLLECTIONS.DISTRICT_COMMITTEES,
    module: 'district_committees',
    title: 'District Committees',
    singular: 'District Committee',
    columns: ['district_name', 'president', 'secretary', 'total_members', 'status'],
    formFields: ['district_name', 'president', 'secretary', 'total_members', 'email', 'mobile', 'description', 'status'],
  },
  employee_issues: {
    collection: COLLECTIONS.EMPLOYEE_ISSUES,
    module: 'employee_issues',
    title: 'Employee Issues',
    singular: 'Issue',
    columns: ['title', 'category', 'status', 'created_at'],
    formFields: ['title', 'category', 'description', 'content', 'status', 'file_url'],
    storagePath: STORAGE_PATHS.DOCUMENTS,
  },
  welfare_schemes: {
    collection: COLLECTIONS.WELFARE_SCHEMES,
    module: 'welfare_schemes',
    title: 'Welfare Schemes',
    singular: 'Scheme',
    columns: ['title', 'category', 'status', 'created_at'],
    formFields: ['title', 'category', 'description', 'content', 'status', 'image', 'file_url', 'link_url'],
    storagePath: STORAGE_PATHS.WEBSITE,
  },
  government_orders: {
    collection: COLLECTIONS.GOVERNMENT_ORDERS,
    module: 'government_orders',
    title: 'Government Orders',
    singular: 'Document',
    columns: ['title', 'category', 'status', 'created_at'],
    formFields: ['title', 'go_category', 'description', 'status', 'go_pdf'],
    storagePath: STORAGE_PATHS.DOCUMENTS,
  },
  grievances: {
    collection: COLLECTIONS.GRIEVANCES,
    module: 'grievances',
    title: 'Grievances',
    singular: 'Grievance',
    columns: ['category', 'name', 'district', 'status', 'created_at'],
    formFields: ['category', 'name', 'message', 'status', 'reply'],
  },
  contact_messages: {
    collection: COLLECTIONS.CONTACT_MESSAGES,
    module: 'contact_messages',
    title: 'Contact Messages',
    singular: 'Message',
    columns: ['name', 'email', 'subject', 'status', 'created_at'],
    formFields: ['name', 'email', 'subject', 'message', 'status', 'reply'],
    readOnlyForm: true,
  },
  website_statistics: {
    collection: COLLECTIONS.WEBSITE_STATISTICS,
    module: 'website_statistics',
    title: 'Homepage Statistics',
    singular: 'Statistic',
    columns: ['label', 'value', 'suffix', 'display_order', 'is_active'],
    formFields: ['label', 'value', 'suffix', 'display_order', 'is_active'],
  },
  website_quick_actions: {
    collection: COLLECTIONS.WEBSITE_QUICK_ACTIONS,
    module: 'website_quick_actions',
    title: 'Quick Action Cards',
    singular: 'Quick Action',
    columns: ['title', 'link', 'display_order', 'is_active'],
    formFields: ['title', 'description', 'icon', 'color', 'link', 'display_order', 'is_active'],
  },
  sponsors: {
    collection: COLLECTIONS.SPONSORS,
    module: 'sponsors',
    title: 'Sponsors',
    singular: 'Sponsor',
    columns: ['name', 'description', 'display_order', 'is_active'],
    formFields: ['name', 'description', 'sponsor_logo', 'display_order', 'is_active'],
    storagePath: STORAGE_PATHS.WEBSITE,
  },
};

export const getFieldDef = (key) => baseFields[key];

export const getModuleConfig = (key) => MODULES[key];
