/** Feature permission keys — synced with Android SubscriptionPermissions */
export const PERMISSION_KEYS = [
  { key: 'can_read_news', label: 'Read News' },
  { key: 'can_watch_live', label: 'Watch Live Streams' },
  { key: 'can_view_gallery', label: 'View Gallery' },
  { key: 'can_watch_videos', label: 'Watch Videos' },
  { key: 'can_download_files', label: 'Download Documents' },
  { key: 'can_view_events', label: 'View Events' },
  { key: 'can_receive_notifications', label: 'Receive Notifications' },
  { key: 'can_comment', label: 'Comment' },
  { key: 'can_like', label: 'Like' },
  { key: 'can_share', label: 'Share' },
  { key: 'can_create_posts', label: 'Create Posts' },
  { key: 'can_upload_images', label: 'Upload Images' },
  { key: 'can_upload_videos', label: 'Upload Videos' },
  { key: 'can_create_events', label: 'Create Events' },
  { key: 'can_publish_announcements', label: 'Publish Announcements' },
  { key: 'can_view_premium', label: 'View Premium Content' },
  { key: 'can_coordinator_dashboard', label: 'Coordinator Dashboard' },
  { key: 'can_send_announcements', label: 'Send Announcements' },
  { key: 'can_manage_volunteers', label: 'Manage Volunteers' },
  { key: 'can_view_reports', label: 'View Reports' },
  { key: 'can_create_polls', label: 'Create Polls' },
  { key: 'can_access_leader_directory', label: 'Access Leader Directory' },
  { key: 'can_manage_local_gallery', label: 'Manage Local Gallery' },
  { key: 'can_view_analytics', label: 'View Analytics' },
];

export const MEMBER_PLAN_PERMISSIONS = {
  can_read_news: true,
  can_watch_live: true,
  can_view_gallery: true,
  can_watch_videos: true,
  can_download_files: true,
  can_view_events: true,
  can_receive_notifications: true,
  can_comment: true,
  can_like: true,
  can_share: true,
  can_create_posts: false,
  can_upload_images: false,
  can_upload_videos: false,
  can_create_events: false,
  can_publish_announcements: false,
  can_view_premium: false,
  can_coordinator_dashboard: false,
  can_send_announcements: false,
  can_manage_volunteers: false,
  can_view_reports: false,
  can_create_polls: false,
  can_access_leader_directory: true,
  can_manage_local_gallery: false,
  can_view_analytics: false,
};

export const COORDINATOR_PLAN_PERMISSIONS = {
  ...MEMBER_PLAN_PERMISSIONS,
  can_create_posts: true,
  can_upload_images: true,
  can_upload_videos: true,
  can_create_events: true,
  can_publish_announcements: true,
  can_coordinator_dashboard: true,
  can_manage_local_gallery: true,
  can_view_analytics: true,
  can_create_polls: true,
  can_send_announcements: true,
};

export const emptyPermissions = () =>
  PERMISSION_KEYS.reduce((acc, { key }) => ({ ...acc, [key]: false }), {});
